Collection management UI
HC-IPPM/safe-inputs pull request #578
Opened 2024-09-09 17:17 UTC by niranjan-ramesh

Addresses #408 . Keeping the issue open to figure out how the conditions for each column of the dataset has to accepted from users. Currently not shown in the form and sends an empty list ```[]```

2024-09-11 13:46 UTC, Stephen-ONeil requested changes
Partial review

2024-09-17 05:37 UTC, niranjan-ramesh commented on ui/src/schema/utils.ts
> +export interface Collection {
Addressed in [63cd011](https://github.com/HC-IPPM/safe-inputs/commit/63cd0113843eb495fcb8d9c737b9610fb1847a7b). Except for the graphql queries and types in the old stuff.

2024-09-17 16:55 UTC, niranjan-ramesh commented on ui/src/components/CollectionForm.tsx
> +function renderEmailFields({
Added separate component for EmailFields in [06b2ef1](https://github.com/HC-IPPM/safe-inputs/pull/578/commits/06b2ef1174ceee30c2636a3d70dc65be0204c41a)[06b2ef1](https://github.com/HC-IPPM/safe-inputs/pull/578/commits/06b2ef1174ceee30c2636a3d70dc65be0204c41a)

2024-09-17 17:07 UTC, niranjan-ramesh commented on ui/src/components/CollectionForm.tsx
> +          </Button>
Refactored with ```aria-label``` in [94ca549](https://github.com/HC-IPPM/safe-inputs/commit/94ca54934142fe264df4067358e560cf6aafab9f)

2024-09-17 18:31 UTC, Stephen-ONeil commented on ui/src/components/CollectionForm.tsx
> +          </Button>
Remember to import and add the lingui template tag `t` to text strings (outside of `<trans>` tags), so lingui can pick them up!

2024-09-19 18:14 UTC, niranjan-ramesh commented on ui/src/components/CollectionForm.tsx
> +        </Button>
Chakra's [```Button```](https://v2.chakra-ui.com/docs/components/button/props#:~:text=string%20%7C%20JSXElementConstructor%3Cany%3E%3E-,loadingText,-Description) has a ```loadingText``` prop that renders a span inside the button when ```loading``` is true. I've set the prop in [f118b77](https://github.com/HC-IPPM/safe-inputs/pull/578/commits/f118b77ad90e2901b1dd154a770c22f4c05e4b5f).

2024-09-19 18:16 UTC, niranjan-ramesh commented on ui/src/components/CollectionForm.tsx
> +    }
The mutation state does indeed capture the error when its fired. I've removed the ```try```/```catch``` in [f118b77](https://github.com/HC-IPPM/safe-inputs/pull/578/commits/0c7b0c83434cf2e3b41c6d1aefed045bc4649dae).

2024-09-19 20:12 UTC, merged