feat: improved accessibility scanning in CI
HC-IPPM/safe-inputs pull request #831
Opened 2024-10-29 13:27 UTC by LilaKelland

Addressing issue #782 

- [ ] Add tests
- [ ] Seed database to activate all routes 
- [ ] Add test for bilingual aria labels
- [ ] Add paragraph to devsecops readme (unless we'd like to include more for each....)

2024-11-06 18:59 UTC, LilaKelland commented on api/src/seed_dev_data.ts
Had copied 'insert records' from your code above, curious why its done in two steps, I tried combining them and it didn't end up triggering the scan of 'upload-records'.

2024-11-06 19:00 UTC, LilaKelland commented on axe-testing/package-lock.json
These files were moved into devsecops/axe-testing

2024-11-06 19:22 UTC, LilaKelland commented on devsecops/axe-testing/Dockerfile.tests
This is just used for tests (runs both unit and the one e2e), but it's basically the same as the Dockerfile for the application, with the exception of the CMD.  I'm using a dockerfile so there's no need to install puppeteer locally, but it seems like duplication - is there a better way to do this?

2024-11-06 20:52 UTC, Stephen-ONeil commented on api/src/seed_dev_data.ts
Combining which steps and how exactly?

2024-11-06 20:59 UTC, Stephen-ONeil commented on devsecops/axe-testing/Dockerfile.tests
If only the `CMD` differs, you can pass an override command option to `docker run`. Check `docker run --help`, the command, note it's not as an options flag, you just include the command following the image name.

2024-11-06 21:10 UTC, LilaKelland commented on api/src/seed_dev_data.ts
Sorry that wasn't clear at all.   There's now 2 insert_records (that works and populates the data to trigger the scan on the manage_records pages) - this is the same as user_1/ owner_1 above in this file)

 await insert_records(user_axe, collection_axe, [
  { column_1: 1, column_2: 2 },
  { column_1: 3, column_2: 4 },
  { column_1: 5, column_2: 6 },
]);

await insert_records(user_axe, collection_axe, [
  { column_1: 7, column_2: 8 },
  { column_1: 9, column_2: 10 },
  { column_1: 11, column_2: 12 },
]); 

 but when I tried to combine them into one insert_records:  

await insert_records(user_axe, collection_axe, [
  { column_1: 1, column_2: 2 },
  { column_1: 3, column_2: 4 },
  { column_1: 5, column_2: 6 },
  { column_1: 7, column_2: 8 },
  { column_1: 9, column_2: 10 },
  { column_1: 11, column_2: 12 },
]);

It didn't trigger the scan of the additional pages.  I'm assuming I may have had a syntax error or something like that, but was wondering if there was different specific reason it was spilt out above with the owner_1/user_1?

2024-11-06 21:19 UTC, LilaKelland commented on devsecops/axe-testing/Dockerfile.tests
Very cool!  On second glance, the testing one isn't running as root and installs the extra test files and config, so slightly different..... maybe I'll try to run tests as non-root tomorrow and see about combining them - thanks!

2024-11-06 21:31 UTC, Stephen-ONeil commented on api/src/seed_dev_data.ts
I believe I did two separate inserts to have some variation in the creation time stamps, shouldn't have any other impact, hmm.

There also aren't currently any routes that are dependent on the existence of columns either. The `upload-records` route placeholder should exist as long as any collections exist for the signed in user (either as owner or uploader). 

Syntax looks fine too. Could you try to recreate it and let me know if you still have the same issue? Could be something weird that's not occurring to me, would be good to know about, thanks!

2024-11-06 22:24 UTC, Stephen-ONeil requested changes
> If this is an okay set up - will need to add the devsecops cloudbuild trigger
I think it can be part of the root cloud build trigger :+1: 

The e2e test is more of a "dependency test" right now, just asserting that puppeteer and axe work together. Dependency tests can be worth doing in some cases, but it'd be ideal here for the end to end test to exercise crawl-page.js and process-axe-report.js altogether, and then assert that the final output is as expected. It'll test the dependencies in the process, but also that the real output of a `AxePuppeteer` run works with your other steps. :+1: 

Parts of `index.js` might need to be recreated, without the safe-inputs specific portions, to do this, right? That'd be fine for now, but you can take challenges like that when writing tests as an indication that the structure of the code itself can be refine,  i.e. in this case, to separate run time context (safe inputs) specific code/configuration from the abstract function of the axe-testing code (crawling a generic site and noting a11y issues).

 Happy to discuss further on a call!

2024-11-06 22:26 UTC, Stephen-ONeil commented on devsecops/axe-testing/package.json
> +    "test:e2e": "npm run test:e2e:startServer && npm run test:e2e:waitForSeverToStart && npm run test:e2e:runTests && npm run test:e2e:stop",
Should be able to start the http server as a pre-test step inside the e2e test, and clean it up at the end, I think!

2024-11-19 21:28 UTC, Stephen-ONeil requested changes
Sorry, vacation last week wiped my brain, I know we discussed possibly reorganizing the axe testing entry point to isolate the safe-inputs details (login flow) from the generic crawling and axe scanning code. Was there anything else that we discussed as possibly in scope for this PR?

Looking at it with a "fresh" mind (for better or worse :sweat_smile:) I'm fine with leaving that for a further follow-up step, perhaps closer to when we think this axe scanning pattern might mature in to something standalone/reusable. Only one thing that jumped right out to me otherwise.

2024-11-19 21:38 UTC, LilaKelland commented on devsecops/axe-testing/jest.config.cjs
> +  testTimeout: 60000, // Increase timeout for e2e test
Thanks!  I'll take a look at this tomorrow.  I think it was mostly the entry point, but that sounds good.

2024-11-20 20:51 UTC, Stephen-ONeil approved these changes
Last optional thought, feel free to take it or not but approved either way. Now that there's separate e2e and unit test config files, you could encode test type in the file paths and match on that, e.g. `*.test.e2e.js` and `*.test.unit.js`. 

It might also be worth renaming `devsecops/axe-testing/tests` to `.../e2e-tests` too, just so future devs don't get confused about what tests live where.

2024-11-21 19:51 UTC, LilaKelland commented
Thanks Stephen!  That's a good idea - changed the names but then my modifications to eslint.config.mjs for the new test file names weren't working, so switched back to .eslintrc (and sending back for review before merging)

2024-11-21 20:15 UTC, merged